services:
  voicevox:
    image: voicevox/voicevox_engine:cpu-latest
    ports:
      - '50021:50021'
    networks:
      - external

  python:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - USERID=${USERID}
        - GROUPID=${GROUPID}
        - USERNAME=${USERNAME}
    tty: true
    stdin_open: true
    volumes:
      - .:/work
      - ~/.claude.json:/home/${USERNAME}/.claude.json
      - models:/root/.cache/huggingface/hub
      - claude:/home/${USERNAME}/.claude
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - '8000:8000'
    networks:
      - external

volumes:
  models:
  claude:

networks:
  external:
    external: true
