services:
  python:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - USERID=${USERID}
        - GROUPID=${GROUPID}
        - USERNAME=${USERNAME}
    tty: true
    stdin_open: true
    volumes:
      - ./work:/home/${USERNAME}/work
      - ./models:/root/.cache/huggingface/hub
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - '8000:8000'
    networks:
      - external

networks:
  external:
    external: true
